### ISSUE TITLE
osx

### ISSUE THREAD

**Issue by mmcd** [UrDHT/PyUrDHT#47]
requests is not part of the install with python3 using homebrew
pip3 install requests fixes

**Comment by BrendanBenshoof** [comment]
can you post the error messages, I thought we had vendor-ed requests into the repo.

**Comment by mmcd** [comment]
it just complains about the module not being found.

**Comment by BrendanBenshoof** [comment]
It should list a file and line number to go with it.

**Comment by mmcd** [comment]
ok. well start to keyboard interrupt on a fresh install of python3 pulled from homebrew on a fresh install of OSX, with a fresh clone of the repo (yes, I changed the conf file)

python3 main.py 
ping
trying http://45.79.205.125:8002/api/v0/peer/ping
"PONG"
Joining Network
joined with: [{"id":"QmZAanMgeVCDL4ohdgpPNBwv72G51HDzHGFgzRboF49Wo5", "addr":"http://45.79.205.125:8002/", "wsAddr":"ws:/45.79.205.125:8003"}, {"id":"Qma398WBMbK3zx86itr6FFivoDs3Cf6RY8t7TcXZU8Kjpv", "addr":"http://131.96.131.65:8000/", "wsAddr":"ws:/131.96.131.65:8001"}]
short [{"id":"QmZAanMgeVCDL4ohdgpPNBwv72G51HDzHGFgzRboF49Wo5", "addr":"http://45.79.205.125:8002/", "wsAddr":"ws:/45.79.205.125:8003"}, {"id":"Qma398WBMbK3zx86itr6FFivoDs3Cf6RY8t7TcXZU8Kjpv", "addr":"http://131.96.131.65:8000/", "wsAddr":"ws:/131.96.131.65:8001"}]
{{"id":"QmZAanMgeVCDL4ohdgpPNBwv72G51HDzHGFgzRboF49Wo5", "addr":"http://45.79.205.125:8002/", "wsAddr":"ws:/45.79.205.125:8003"}, {"id":"Qma398WBMbK3zx86itr6FFivoDs3Cf6RY8t7TcXZU8Kjpv", "addr":"http://131.96.131.65:8000/", "wsAddr":"ws:/131.96.131.65:8001"}}
Node up and Running
ping
trying http://45.79.205.125:8002/api/v0/peer/ping
ping
trying http://131.96.131.65:8000/api/v0/peer/ping
{"id":"Qmc9cgNy3VsKUQW6HYwnCcRUW4ty6y56tykDBCKbhH8UqP", "addr":"http://10.1.1.10:8000/", "wsAddr":"ws:/10.1.1.10:8001"}
about to map
started websocket proxy
done mapping
"PONG"
The Post Worked
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(_self._args, *_self._kwargs)
  File "/Users/michael/Git/PyUrDHT/websocketProxy.py", line 20, in main
    import requests
ImportError: No module named 'requests'
"PONG"
The Post Worked
^CException ignored in: <module 'threading' from '/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by BrendanBenshoof** [comment]
thanks, looks like into the websocket code.
